## 作业内容
基本要求：
●使用sklearn 的 MLP 实现神经网络


-数据要求：

-回归问题：

-选取任意标准数据集测试

提高练习：

●尝试使用pytorch实现梯度下降（先手动update，再使用torch.optim模块）

●(有独显者)尝试使用 cuda ，对比GPU与CPU的运行效率

●尝试手动实现梯度下降（难）


In [1]:
import pandas as pd
df1=pd.read_excel(r"C:\Users\lenovo\Downloads\Data1-train.xlsx",header=0)
df1.head()

S_L  S_W  P_L  P_W  response
0  5.1  3.5  1.4  0.2         0
1  4.9  3.0  1.4  0.2         0
2  4.7  3.2  1.3  0.2         0
3  4.6  3.1  1.5  0.2         0
4  5.0  3.6  1.4  0.2         0

### 分类说明: 山鸢尾:0，变色鸢尾:1

In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report
X = df1[['S_L', 'S_W', 'P_L', 'P_W']].values.astype(float)  
y = df1['response'].values.astype(float) 
print(X)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.

## 代码封装

In [ ]:
def MLP_regressor(X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    mlp = MLPClassifier(hidden_layer_sizes=(1), max_iter=1000, random_state=42,shuffle=False)
    mlp.fit(X_train, y_train)
    y_pred = mlp.predict(X_test)
    print(classification_report(y_test, y_pred))

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
X_tensor = torch.FloatTensor(X)
y_tensor = torch.FloatTensor(y).view(-1, 1)
class first_NN(nn.Module):
    def __init__(self):
        super(first_NN, self).__init__()
        self.hidden1 = nn.Linear(4, 5)   
        self.output = nn.Linear(5, 1)     

    def forward(self, x):
        x = torch.relu(self.hidden1(x))
        x = self.output(x)
        return x
def Network(X,y,learning_rate,epochs):#手动更新
    model = first_NN()
    criterion = nn.MSELoss()

    for epoch in range(epochs):
        model.train()
        outputs = model(X) 
        loss = criterion(outputs, y)
        if epoch % 100 == 0:
            print("第{}次训练损失为{}".format(epoch,loss))  
        model.zero_grad() 
        loss.backward() 
        with torch.no_grad():  
            for param in model.parameters():
                param -= learning_rate * param.grad 
    print("最终损失为", loss.item())

def auto_Network(X,y,lrs,epochs):#自动更新
    model=first_NN()
    loss_fuction=nn.MSELoss()
    optimizer = optim.SGD(model.parameters(), lr=lrs)
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        outputs=model(X)
        loss=loss_fuction(outputs,y)
        if epoch % 100 == 0:
            print("第{}次训练损失为{}".format(epoch,loss))  
        loss.backward()
        optimizer.step()
    print("最终损失为", loss.item())
        



## 运行结果


In [5]:
MLP_regressor(X,y)

              precision    recall  f1-score   support

         0.0       0.67      1.00      0.80        12
         1.0       0.00      0.00      0.00         6

    accuracy                           0.67        18
   macro avg       0.33      0.50      0.40        18
weighted avg       0.44      0.67      0.53        18



d:\tools\miniforge\envs\pytorch\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\tools\miniforge\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\tools\miniforge\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\tools\miniforge\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetric

In [6]:
Network(X_tensor,y_tensor,0.01,1000)

第0次训练损失为0.5978603363037109
第100次训练损失为0.2687149941921234
第200次训练损失为0.2527337968349457
第300次训练损失为0.2456016093492508
第400次训练损失为0.23565198481082916
第500次训练损失为0.21727043390274048
第600次训练损失为0.18414020538330078
第700次训练损失为0.1268232762813568
第800次训练损失为0.046024397015571594
第900次训练损失为0.013048301450908184
最终损失为 0.011230399832129478


In [7]:
auto_Network(X_tensor,y_tensor,0.01,1000)

第0次训练损失为0.3093295097351074
第100次训练损失为0.0647267997264862
第200次训练损失为0.01928802765905857
第300次训练损失为0.012826095335185528
第400次训练损失为0.011867528781294823
第500次训练损失为0.011560841463506222
第600次训练损失为0.01133897714316845
第700次训练损失为0.011140769347548485
第800次训练损失为0.010957338847219944
第900次训练损失为0.010786240920424461
最终损失为 0.010627596639096737


## 实验总结





#### 实验结果
- 在回归任务中，通过调整神经网络的结构和超参数，能够有效降低模型的损失，得到较好的预测效果。
- 在分类任务中，神经网络表现出优于传统逻辑回归的方法，尤其是在复杂数据集上。
- 使用torch.optim模块简化了模型训练过程，并提供了更好的可读性和维护性。

#### 体会与反思
- 模型选择：不同的神经网络结构和参数对模型性能有显著影响，合理选择隐含层和节点数是关键，但是对于我们这次二分类问题并不是那么明显。
- 损失函数：选择适合的损失函数（如MSE和交叉熵）对模型训练效果至关重要。
- 调试与优化：在使用PyTorch时，掌握梯度计算与更新机制是理解深度学习的重要基础。
- 对于代码的理解: 知道了为什么要进行梯度清零，是未来防止上一次迭代的梯度对该次迭代造成影响，所以必须在反向传播之前进行梯度清零；为什么要no_grad，一般是在检验时提高效率。



通过本次实验，加深了对神经网络原理及其实现的理解，以及我自己的构建简单神经网络模型的能力为进一步的学习与研究打下了基础。